default_platform(:ios)

platform :ios do
    lane :unit_test do
        scan(
            output_types: "html",
            output_directory: "archive/unit_test",
            code_coverage: true
        )

        slather(
            proj: "Markdown-iOS.xcodeproj",
            workspace: "Markdown-iOS.xcworkspace",
            scheme: "Markdown-iOS",
            configuration: "Debug",
            output_directory: "archive/coverage",
            html: true,
            ignore: ["Pods/**"]
        )
    end
end
